### ISSUE TITLE
Load images dynamically

### ISSUE THREAD

**Issue by ganziqim** [NiX-Team/NiX#2]
可能是因为github.io带宽有限，目前图片加载时间太长（接近30s），需要改为动态加载，或者对图片进行压缩

**Comment by MadratJerry** [comment]
添加了一个临时的解决方案，改进了首屏的显示速度

**Comment by ganziqim** [comment]
@crazymousethief 直接把图片加载移除了？

**Comment by MadratJerry** [comment]
移除了了 preloader，背景图最后还是会加载的
